# Steps on how to run our system/typeline to run the software

name: '[CI] Continuous Integration'

# Commit/pull request open
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3
      ## =================
      - name: 'Debug'
        run: |
          ls -la
          echo "Segundo comando de debug"
      - name: 'Install Dependencies'
        run: 'npm install'
      - name: 'Lint'
        run: 'npm run lint'
