# Automates the continuous delivery process for software

name: '[CD] Continuous Delivery'

# Commits/pushes occur on the "main" branch

on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: k6xK6QiqBibt79HaeKXOvU22
  VERCEL_PROJECT_ID: prj_bRr3wf8CLMAQBgqWABXcRBYFESPk

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3

      - name: 'Debug'
        run: |
          ls -la

      - name: 'Install Dependencies'
        run: 'npm install'

      - name: 'Vercel'
        run: 'npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}'
