# Steps on how to run our system/typeline to run the software

name: '[CD] Continuous Delivery'

# Commit/pull request open

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_Steps]
      - uses: actions/checkout@v3

      - name: 'Debug'
        run: |
          ls -la

      - name: 'Install Dependencies'
        run: 'npm install'

      - name: 'Vercel'
        run: 'npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --org=${{ secrets.VERCEL_ORG_ID }} --prod-${{ secrets.VERCEL_PROJECT_ID }}'
